apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tentomushi-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pulkitdubey-meesho/tentomushi-deploy.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
